services:
  postgres:
    image: postgres:16.1
    env_file:
      - .env.local
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'workshop-helper'
      POSTGRES_USER: 'workshop-helper'
      POSTGRES_PASSWORD: 'workshop-helper'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U workshop-helper']
      interval: 10s
      timeout: 5s
      retries: 5
